# Generated by Django 2.2.6 on 2019-10-10 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='id_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_evenement', to='api_flutter.Events'),
        ),
    ]
