# Generated by Django 2.2.6 on 2019-10-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0002_auto_20191010_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='id_commune',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commune_utilisateur', to='api_flutter.Commune'),
        ),
    ]
