# Generated by Django 2.2.6 on 2019-10-10 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0003_auto_20191010_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.URLField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_event', to='api_flutter.Events')),
            ],
        ),
    ]
