# Generated by Django 2.2.6 on 2019-10-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_flutter', '0004_imageevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageevents',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageevents',
            name='date_upd',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imageevents',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
